### ISSUE TITLE
No access to my documents, annotations and labels

### ISSUE THREAD

**Issue by izadorapimenta** [forTEXT/catma#312] opened 2022-04-26 09:36 UTC
**Describe the bug**

When I enter my documents and annotations section, I have no access to my documents and I can not visualise or edit my labels. Basically, I do not have access to my entire work.

![imagem](https://user-images.githubusercontent.com/22567821/165270436-9268bf6c-978e-45cf-ad8d-fca147909bdb.png)

**Comment by maltem-za** [comment] 2022-04-26 09:59
Hello, thank you for the report. We have emailed you directly about this problem with your project.

I am closing this issue as a duplicate of #310

**Closed by maltem-za** 2022-04-26 09:59 UTC
