### ISSUE TITLE
Error "Missing unknown 0000..." for newly created resources

### ISSUE THREAD

**Issue by TomSgrizzi** [forTEXT/catma#310] opened 2022-01-30 13:32 UTC
**Describe the bug**
After I upload a few documents (.docx or .txt) I get this error and lose access to my project. If I refresh the page, or log in again I still have no access to the project and all the documents uploaded are gone. 

**To Reproduce**
1. Go to 'Project'
2. Click on 'Add Document'
3. Upload them
4. After few uploads the errors appear. It appears immediately with bulk upload. If I try to upload them one by one inevitably after a few it crushes.

**Expected behavior**
I should be able to upload my documents, work on them and access my project 

**Screenshots or screen recording**
I attached screenshots

**Information about your environment**
 - OS: Win11
 - Browser Chrome

**Additional context**
![Screenshot (1111)](https://user-images.githubusercontent.com/98694781/151701866-b19fb6c3-8936-4157-b54e-92f64f3e8b60.png)
![Screenshot (1113)](https://user-images.githubusercontent.com/98694781/151701867-d6a5231f-5836-49f4-8a0e-b4e13d641e29.png)

Thanks a lot in advance!

**Comment by maltem-za** [comment] 2022-02-02 18:33
Thank you kindly for the report. We are investigating the root cause of this issue.

In the mean time, we ask that anyone experiencing this error please send an email to support@catma.de with their username / email address that they use to log in to CATMA and the name of the project affected. This will allow us to solve the problem for you in the short term.

**Comment by maltem-za** [comment] 2022-02-02 18:42
The error occurs due to badly initialised submodules when new resources are created. The root cause is not yet known.

Symptoms:
- Staged changes in the root repo
- `git submodule` output containing one or more of the following:
`0000000000000000000000000000000000000000 <resource container directory>/<resource GUID> ()`
- Submodule directory containing only a .git file and nothing else, no commits

Workaround:
- Manually re-add the submodule

**Comment by TomSgrizzi** [comment] 2022-02-05 12:54
Thank you so much! I still have another problem, related to the annotations I applied, which are not saved when I close the project (and stay on CATMA), and when I log out, or simply close the tab. Should I open a new issue and close this one?
Thanks a lot for your help again!

**Comment by maltem-za** [comment] 2022-05-03 15:25
This issue could not be correlated with any of the recent releases or code changes. The root cause remains a mystery, however it appears to be a JGit bug that is somehow influenced by external factors (as it occurs randomly and we weren't able to reproduce it reliably).

A workaround has been implemented, which will go live in the coming days. This issue will remain open until then.

**Comment by maltem-za** [comment] 2022-05-06 15:39
Closing with the release of 6.5.1

**Closed by maltem-za** 2022-05-06 15:39 UTC
Labels: type : bug, priority : high, effort : unknown, module : project
